jobs:
  include:
    - stage: Tests
      name: "Kuzzle Plugin Tests"
      language: node_js
      node_js: 8
      cache:
        directories:
          - ~/.npm
          - ~/.cache
          - node_modules # NPM packages

      install:
        - cd $TRAVIS_BUILD_DIR/explorama/backend
        - npm install --silent --unsafe-perm
        - npm install --silent --unsafe-perm --only=dev

      script:
        - bash features/run-kuzzle-stack.sh
        - npm run lint && npm run unit-testing
