version: '3'

services:
  kuzzle:
    image: kuzzleio/plugin-dev:2
    command: /run-dev.sh
    volumes:
      - "./docker/run-dev.sh:/run-dev.sh"
      - "./docker/install-plugins.sh:/install-plugins.sh"
      - "./fixtures/default-mappings.json:/default-mappings.json"
      - "./fixtures/default-fixtures.json:/default-fixtures.json"
      - "./fixtures/default-securities.json:/default-securities.json"
      - "./config/kuzzlerc:/etc/kuzzlerc"
      - "./config/:/var/app/config/"
      - ".:/var/app/plugins/enabled/kuzzle-plugin-advanced-boilerplate"
    cap_add:
      - SYS_PTRACE
    ulimits:
      nofile: 65536
    sysctls:
      - net.core.somaxconn=8192
    depends_on:
      - redis
      - elasticsearch
    ports:
      - "9229:9229"
      - "7512:7512"
    environment:
      - kuzzle_services__storageEngine__client__node=http://elasticsearch:9200
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - NODE_ENV=development
      - DEBUG=kuzzle:*,-kuzzle:entry-point:protocols:websocket
      - KUZZLE_VAULT_KEY=${KUZZLE_VAULT_KEY}

  redis:
    image: redis:5

  elasticsearch:
    image: kuzzleio/elasticsearch:7
    ports:
      - "9200:9200"
    ulimits:
      nofile: 65536
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=alyx
      - cluster.name=kuzzle
      - discovery.type=single-node
